sudo: required
services:
- docker
script:
- docker run --rm -w "/doc" -v "$PWD":/doc thomasweise/texlive make
- mkdir -p artifacts/$TRAVIS_BRANCH && mv src/*.pdf artifacts/$TRAVIS_BRANCH

deploy:
  provider: s3
  access_key_id: AKIAI7V5LPCQQ3APYQ4Q
  secret_access_key:
    secure: L8uKLakAkgf7iCcj+xIrjzfgVd7BoscDqXHv3iB2DuyWSIgL1BYao720/6dsULX3dT1TrisoN8xMydmghH7LeA+O15oz1jZXx/DQBHJwbyHdK33TRnpcSYybopOIkyoeicqrPJEYFvV/0JzMT0gRiV5VIEX5LZ1mo6R65mh816Z7TlSBLrhQZnTKZojwV/hXAUyVYmE1+aZ8AYbNb5KoWZUjBrFmVmtEuVM7jP4YLoAnfSjntQnpOretj/dyJy/5OqHT7yaoFQDn6obXM+7H7e9HODDUtAxyqWXTGr8YO2Pce4XUJXJwopL6JwKiIC+Ae9NFHpBKQ8drXrDC5gUJMrKFf4wq+Kry6Pu/JlfWP8ozm/Iqv7mzx4Zgh2P6yKcq5i+MS05FHgFkur7dMk0NqrZYpGMEkJr0ddFgF5G3c8tfpj/5zB3VLjpvGBkP+RPctuVa/4UIALqHh6IQHbyjATgUG8QNSWbc6OSEymF8Mzz6I706sFqswBDxkBJzDyjYT9CEakcZM3+mix/nIjzH11Mw4p7j/kXmR0uTQiTht24KFgAUa7TpR/pCQjzRXxAxxEXqKlIBAtsxCRlQYVQc8MkMzUhs3lNPBjcLW0NZgJTwrb9xvmnWUQOKWDvWMjXKTldD8WtVDEExO4y5dW4ta/ZpkorLN2WlAnmz6i79v3w=
  bucket: dl.velimir.me.uk
  region: eu-west-2
  local-dir: artifacts
  upload-dir: cv
  skip_cleanup: true
  on:
    repo: velimir0xff/resume
    all_branches: true
